<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net6.0-windows</TargetFramework>
        <LangVersion>10.0</LangVersion>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <Page Update="Views\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LiveCharts" Version="0.9.7" />
      <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
      <PackageReference Include="System.Management" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="docs\images\" />
    </ItemGroup>

</Project>
